# PHYS 210, Exercise 5
Wed Sept. 18, Due Mon Sept 23, 9 am

Enter the names, and describe the contributions of anybody besides yourself who contributed/collaborated. 

Vihara Jayaweera

## Reading files 1
Using numpy's `loadtxt()` function, read the sample file from lecture, `examplearray.txt`, into an array called `data`. Using the `print()` function, print the data so you can check that all of the data rows are loaded correctly and that the commented lines are ignored. The file is already in the same directory as this notebook.

In [2]:
#YOUR CODE HERE
import numpy as np

data = np.loadtxt('examplearray.txt')
print(data)

[[1.    1.24  3.14  0.012 0.52 ]
 [2.    1.26  3.89  0.012 0.52 ]
 [3.    1.28  4.04  0.012 0.53 ]
 [4.    1.3   4.33  0.012 0.53 ]
 [5.    1.33  4.67  0.012 0.54 ]
 [6.    1.35  5.08  0.012 0.54 ]]


In [2]:
# Test data

## Reading files  2
Write a function, called `get_rows_cols(arr)` that will return two values: the number of rows and columns in a two-dimensional array. To return two values, you can simply: `return rows, cols`. If the array argument is one-dimensional, get_row_cols should return a 1 for the number of rows. If it has more than 2 dimensions, the final two dimensions should be taken to be the rows and columns.

Use your function to set the variables rows, cols with the number of rows and columns in the data array.

In [9]:
def get_rows_cols(arr):
    shape = np.array(np.shape(arr))
    if(shape.size == 1 ):
        rows = 1
        cols = shape[0]
    elif(shape.size == 2):
        rows = shape[0]
        cols = shape[1]
    else:
        rows = arr.shape[len(shape)-2]
        cols = arr.shape[len(shape)-1]
        
    return rows, cols


rows, cols = get_rows_cols(data)
#fixed

(1, 4)


In [4]:
# test that get_rows_cols is defined

In [5]:
# test that get_rows_cols works for 1 d arrays

In [6]:
# test that get_rows_cols works for 2 d arrays

In [7]:
# test get_rows_cols for higher dimension arrays

## Calculations on the array
Calculate the mean of the second column and the variance of the third column in the appropriate variables below. Print the results. You may use your code from Exercise 3, or `numpy.mean()` and `numpy.var()` If you use `numpy.var()` make sure to set the 'delta degrees of freedom' to 1.

In [8]:
col2 = np.loadtxt('examplearray.txt',usecols=(1))
col3 = np.loadtxt('examplearray.txt', usecols=(2))

mean2 = np.mean(col2)
var3 = np.var(col3,ddof=1)


In [9]:
# test mean2

In [10]:
# test var3

## Extracting the header and footer
Read the examplearray.txt file again, this time using the `readlines()` function, which is closely related to `readline()` that appeared in the lecture notes. `readlines()` returns a list of strings, one for each line. Set the string variables `first_line` and `last_line` to be the first and last lines of the file, and print these on the screen to verify that they are the lines you expect. `last_line` should be set correctly even if the number of lines in `examplearray.txt` is changed, ie your code should not rely on the number of lines in the file being any particular value.

In [11]:
f = open("examplearray.txt",'r')
l = f.readlines()
n = len(l)-1

first_line = l[0]
last_line = l[n]


In [12]:
# test first_line

In [13]:
# test last_line

# Formatting text - the old way

The first row of the sample data could be described as:

Data-point number 1 has values of x = 1.24 and y = 3.14, with  errors of 0.012 and 0.52, respectively.

Write a function called `format_data(row)` that will take a row of the data array as an argument and return a sentence such as this. Use the old-style text formatting: %( ).

All of the numbers in the output should come from the row that is passed in. 

Ensure you use the same number of significant digits as in the example sentence above. Proof-read your output carefully to ensure the text matches the example exactly.

In [14]:
import numpy as np
data = np.loadtxt('examplearray.txt')

def format_data(row):
    values = str(row).replace('[','').split()
    return "Data-point number %s has values of x = %s and y = %s, with errors of %s and %s, respectively." % (values[0].replace(".",''),values[1],values[2],values[3], values[4])
   


In [15]:
# test format_data
assert(format_data(data[0,:]) == "Data-point number 1 has values of x = 1.24 and y = 3.14, with errors of 0.012 and 0.52, respectively.")


In [16]:
# Test format_data

## Formatting text - the new way
Repeat this formatting exercise using the 'new style' string formatting (with .format()), writing a new function: `format_data_new(row)`

In [17]:
import numpy as np
data = np.loadtxt('examplearray.txt')

def format_data_new(row):
    values = str(row).replace('[','').split()
    return "Data-point number {} has values of x = {} and y = {}, with errors of {} and {}, respectively.".format(values[0].replace('.',''),values[1],values[2],values[3], values[4])


In [18]:
# test format_data_new

In [19]:
# Test format_data_new

## Writing Files
Write a function, `write_stats(arr, filename)` that takes a one-dimensional array and a string as arguments.  The function should calculate the mean and standard deviation (ddof=1) of the array, and write:
```
Mean = 23.22
Std = 2.42
```
to the file given by the filename. In this function, always use 2 digits after the decimal place. You can use numpy's mean and std (with ddof=1) functions or your own. You can use either new style or old style formatting, but ensure you get the spacing and capitalization exactly right. Remember to include a unix-style carriage return (\n) at the end of each line.

In [20]:
def write_stats(arr, filename):
    mean = np.mean(arr)
    std = np.std(arr, ddof = 1)
    f = open(filename + '.txt','a')
    f.write('Mean = {0:.2f}\n'.format(mean))
    f.write('Std =  {0:.2f}\n'.format(std))


In [21]:
# test write_stats()

In [22]:
# test write_stats()

### Writing files 2
Imagine that the "x" data in the examplearray.txt file is in meters and you would like it to be in millimeters. 
Multiply the x (and xerror) columns by 1000 and save the resulting array into a file called `fixed_example.txt` using `numpy.savetxt()`.

Ensure your new file preserves the first and last comment lines - which you should still have available in first_line and last_line. Double check to make sure the comment lines appear exactly as they did in the original, and that there are no extra comment lines.

The data point number should appear as an integer, the x and xerror fields should also be integers. y and yerror should have the same number of significant digits as they did in the original.


In [23]:
import numpy as np

col0 = np.loadtxt('examplearray.txt', usecols =(0)) #nth row
col4 = np.loadtxt('examplearray.txt', usecols = (4))#yerror
new_x = np.loadtxt('examplearray.txt', usecols = (1))*1000 #x-values
#yvalues store in variable col3 above
new_x_error = (np.loadtxt('examplearray.txt', usecols = (3)))*1000 #xerror
first_line = first_line.replace('\n','')
last_line = last_line.replace('\n','')

nf = open('fixed_example.txt','a+')
np.savetxt('fixed_example.txt',np.c_[col0,new_x,col3,new_x_error,col4],fmt=' %d. %d %.2f %d %.2f', header = first_line, footer = last_line, comments = '')
nf.close()

In [24]:
# test fixed_example.txt

In [25]:
# test values in fixed_example.txt

In [26]:
# test comment lines

Don't forget to 
1. list any contributors and their contributions at the top
2. Save and validate (or restart kernel and run all)
3. Submit!